spring:
  h2:
    console:
      enabled: true

  datasource:
    username: admin
    url: jdbc:mysql://spring1.c3heeyxwi8fd.ap-northeast-2.rds.amazonaws.com:3306/schedule
    password: '!123456789'

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    com.tutorial: debug

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK